/**
 * Catálogo canônico de checks do Monitoring Engine — Foundation v1.
 *
 * Cada `MonitoringCheckDefinition` abaixo é só uma DECLARAÇÃO — nenhuma
 * delas executa rede, DNS, SSL, Supabase, Vercel, VPS, Docker, Redis, WAHA,
 * Chatwoot ou Evolution. Resultados vêm sempre de um `MonitoringAdapter`
 * fake/noop (`adapters.ts`) ou de simulação (`evaluator.ts`).
 *
 * `chatwoot_available`/`evolution_available` referenciam ids de módulo
 * (`channel.chatwoot`/`channel.evolution`) que NÃO existem em
 * `lib/modules/catalog.ts::MODULE_CATALOG` — ficam no catálogo (a doutrina
 * desta Foundation pede as duas entradas), mas `enabledByDefault: false` e,
 * por construção de `resolveApplicableMonitoringChecks`
 * (`requiredModules.every(...)` nunca bate com um módulo inexistente),
 * nenhuma instalação jamais os terá como aplicáveis nesta versão. Ver
 * `docs/monitoring/check-catalog.md`.
 */
import type { MonitoringCheckDefinition } from "./types";

export const MONITORING_CHECK_CATALOG: MonitoringCheckDefinition[] = [
  // --- comuns a todos os planos --------------------------------------------
  {
    id: "application_reachable",
    name: "Aplicação acessível",
    description: "O frontend da instalação responde a uma requisição básica.",
    category: "application",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "application_health_endpoint",
    name: "Endpoint de saúde da aplicação",
    description: "O endpoint de health check da aplicação responde com sucesso.",
    category: "application",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "domain_configured",
    name: "Domínio configurado",
    description: "O domínio da instalação está configurado e apontado corretamente.",
    category: "domain",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "warning",
    expectedCadence: "manual",
    enabledByDefault: true,
  },
  {
    id: "dns_resolves",
    name: "DNS resolve",
    description: "O domínio da instalação resolve pro endereço esperado.",
    category: "dns",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "critical",
    expectedCadence: "daily",
    enabledByDefault: true,
  },
  {
    id: "ssl_valid",
    name: "Certificado SSL válido",
    description: "O certificado SSL do domínio é válido e confiável.",
    category: "ssl",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "critical",
    expectedCadence: "daily",
    enabledByDefault: true,
  },
  {
    id: "ssl_expiration",
    name: "Validade do certificado SSL",
    description: "O certificado SSL não está próximo de expirar.",
    category: "ssl",
    appliesToPlans: ["lite", "pro", "dedicated"],
    dependsOn: ["ssl_valid"],
    severityWhenFailed: "warning",
    expectedCadence: "daily",
    enabledByDefault: true,
  },
  {
    id: "authentication_available",
    name: "Autenticação disponível",
    description: "O provedor de autenticação da instalação está disponível.",
    category: "authentication",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "database_reachable",
    name: "Banco de dados acessível",
    description: "O banco de dados da instalação aceita conexões.",
    category: "database",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "storage_available",
    name: "Storage disponível",
    description: "O armazenamento de arquivos/mídia da instalação está disponível.",
    category: "storage",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "warning",
    expectedCadence: "daily",
    enabledByDefault: true,
  },
  {
    id: "owner_access_configured",
    name: "Acesso do responsável configurado",
    description: "Existe pelo menos um usuário admin/owner com acesso configurado na instalação.",
    category: "authentication",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "warning",
    expectedCadence: "manual",
    enabledByDefault: true,
  },
  {
    id: "module_configuration_consistent",
    name: "Configuração de módulos consistente",
    description: "Os módulos habilitados da instalação são compatíveis com o plano e suas dependências.",
    category: "monitoring",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "warning",
    expectedCadence: "daily",
    enabledByDefault: true,
  },
  {
    id: "deployment_manifest_consistent",
    name: "Manifesto de implantação consistente",
    description: "O manifesto de implantação da instalação não tem blockers/divergências pendentes.",
    category: "monitoring",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "warning",
    expectedCadence: "manual",
    enabledByDefault: true,
  },
  {
    id: "provisioning_completed",
    name: "Provisionamento concluído",
    description: "O plano de provisionamento da instalação foi concluído sem etapas obrigatórias pendentes.",
    category: "monitoring",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "critical",
    expectedCadence: "manual",
    enabledByDefault: true,
  },
  {
    id: "backup_recent",
    name: "Backup recente",
    description: "Existe um backup concluído dentro da janela esperada.",
    category: "backup",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "warning",
    expectedCadence: "daily",
    enabledByDefault: true,
  },
  {
    id: "monitoring_configured",
    name: "Monitoramento configurado",
    description: "A instalação tem monitoramento configurado (mesmo que só nesta Foundation, em memória).",
    category: "monitoring",
    appliesToPlans: ["lite", "pro", "dedicated"],
    severityWhenFailed: "info",
    expectedCadence: "manual",
    enabledByDefault: true,
  },

  // --- Lite / Pro -----------------------------------------------------------
  {
    id: "frontend_deployment_available",
    name: "Deploy de frontend disponível",
    description: "O deploy do frontend hospedado (Vercel/Cloudflare) está disponível.",
    category: "application",
    appliesToPlans: ["lite", "pro"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "supabase_project_configured",
    name: "Projeto Supabase configurado",
    description: "A instalação tem um projeto Supabase próprio configurado (referência, não segredo).",
    category: "database",
    appliesToPlans: ["lite", "pro"],
    severityWhenFailed: "critical",
    expectedCadence: "manual",
    enabledByDefault: true,
  },
  {
    id: "supabase_auth_available",
    name: "Supabase Auth disponível",
    description: "O serviço de autenticação do projeto Supabase da instalação está disponível.",
    category: "authentication",
    appliesToPlans: ["lite", "pro"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "supabase_database_available",
    name: "Supabase Database disponível",
    description: "O banco Postgres do projeto Supabase da instalação está disponível.",
    category: "database",
    appliesToPlans: ["lite", "pro"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "supabase_storage_available",
    name: "Supabase Storage disponível",
    description: "O Storage do projeto Supabase da instalação está disponível.",
    category: "storage",
    appliesToPlans: ["lite", "pro"],
    severityWhenFailed: "warning",
    expectedCadence: "daily",
    enabledByDefault: true,
  },
  {
    id: "managed_cron_configured",
    name: "Cron gerenciado configurado",
    description: "O cron gerenciado (scheduler sem worker dedicado) está configurado, quando exigido por módulo.",
    category: "scheduler",
    appliesToPlans: ["lite", "pro"],
    requiresInfra: ["scheduler"],
    severityWhenFailed: "warning",
    expectedCadence: "manual",
    enabledByDefault: true,
  },
  {
    id: "edge_functions_available",
    name: "Edge Functions disponíveis",
    description: "Edge Functions do projeto Supabase estão disponíveis, quando exigidas por módulo (tipicamente Pro).",
    category: "integration",
    appliesToPlans: ["lite", "pro"],
    requiresInfra: ["edgeFunctions"],
    severityWhenFailed: "info",
    expectedCadence: "daily",
    enabledByDefault: true,
  },

  // --- Dedicated --------------------------------------------------------------
  {
    id: "vps_reachable",
    name: "VPS acessível",
    description: "A VPS exclusiva da instalação responde.",
    category: "application",
    appliesToPlans: ["dedicated"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "runtime_available",
    name: "Runtime disponível",
    description: "O runtime da aplicação (processo Next.js/Docker) está de pé na VPS.",
    category: "application",
    appliesToPlans: ["dedicated"],
    dependsOn: ["vps_reachable"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "reverse_proxy_available",
    name: "Proxy reverso disponível",
    description: "O proxy reverso (Caddy) da instalação está de pé e servindo TLS.",
    category: "application",
    appliesToPlans: ["dedicated"],
    dependsOn: ["vps_reachable"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "redis_available",
    name: "Redis disponível",
    description: "O Redis da instalação está disponível, quando a instalação exige Redis.",
    category: "redis",
    appliesToPlans: ["dedicated"],
    requiresInfra: ["redis"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "worker_running",
    name: "Worker rodando",
    description: "O worker dedicado da instalação está rodando, quando algum módulo exige worker.",
    category: "worker",
    appliesToPlans: ["dedicated"],
    requiresInfra: ["worker"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "scheduler_running",
    name: "Scheduler rodando",
    description: "O scheduler dedicado da instalação está rodando, quando algum módulo exige scheduler.",
    category: "scheduler",
    appliesToPlans: ["dedicated"],
    requiresInfra: ["scheduler"],
    severityWhenFailed: "warning",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "backup_job_configured",
    name: "Job de backup configurado",
    description: "Existe um job de backup agendado configurado na VPS da instalação.",
    category: "backup",
    appliesToPlans: ["dedicated"],
    severityWhenFailed: "warning",
    expectedCadence: "manual",
    enabledByDefault: true,
  },
  {
    id: "disk_capacity",
    name: "Capacidade de disco",
    description: "O uso de disco da VPS está dentro do limite seguro.",
    category: "application",
    appliesToPlans: ["dedicated"],
    severityWhenFailed: "warning",
    expectedCadence: "daily",
    enabledByDefault: true,
  },
  {
    id: "memory_capacity",
    name: "Capacidade de memória",
    description: "O uso de memória da VPS está dentro do limite seguro.",
    category: "application",
    appliesToPlans: ["dedicated"],
    severityWhenFailed: "warning",
    expectedCadence: "daily",
    enabledByDefault: true,
  },
  {
    id: "service_restart_policy",
    name: "Política de reinício do serviço",
    description: "O serviço systemd/Docker da aplicação tem política de reinício automático configurada.",
    category: "application",
    appliesToPlans: ["dedicated"],
    severityWhenFailed: "info",
    expectedCadence: "manual",
    enabledByDefault: true,
  },

  // --- canais -----------------------------------------------------------------
  {
    id: "email_provider_configured",
    name: "Provedor de e-mail configurado",
    description: "O provedor de e-mail transacional está configurado, quando o canal de e-mail está ativo.",
    category: "email",
    appliesToPlans: ["lite", "pro", "dedicated"],
    requiredModules: ["channel.email"],
    severityWhenFailed: "warning",
    expectedCadence: "manual",
    enabledByDefault: true,
  },
  {
    id: "whatsapp_channel_configured",
    name: "Canal WhatsApp configurado",
    description: "O canal WhatsApp da instalação está configurado, quando o módulo channel.whatsapp está ativo.",
    category: "whatsapp",
    appliesToPlans: ["dedicated"],
    requiredModules: ["channel.whatsapp"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "waha_available",
    name: "WAHA disponível",
    description: "A instância WAHA da instalação está disponível, quando o módulo channel.whatsapp está ativo.",
    category: "waha",
    appliesToPlans: ["dedicated"],
    requiredModules: ["channel.whatsapp"],
    severityWhenFailed: "critical",
    expectedCadence: "hourly",
    enabledByDefault: true,
  },
  {
    id: "chatwoot_available",
    name: "Chatwoot disponível",
    description:
      "Reservado pra um futuro canal Chatwoot — referencia o módulo channel.chatwoot, que ainda não existe " +
      "no Module Engine. Nunca aplicável nesta versão (ver docs/monitoring/check-catalog.md).",
    category: "chatwoot",
    appliesToPlans: ["dedicated"],
    requiredModules: ["channel.chatwoot"],
    severityWhenFailed: "warning",
    expectedCadence: "hourly",
    enabledByDefault: false,
  },
  {
    id: "evolution_available",
    name: "Evolution disponível",
    description:
      "Reservado pra um futuro canal Evolution — referencia o módulo channel.evolution, que ainda não existe " +
      "no Module Engine. Nunca aplicável nesta versão (ver docs/monitoring/check-catalog.md).",
    category: "evolution",
    appliesToPlans: ["dedicated"],
    requiredModules: ["channel.evolution"],
    severityWhenFailed: "warning",
    expectedCadence: "hourly",
    enabledByDefault: false,
  },
];

export function getMonitoringCheckDefinition(id: string): MonitoringCheckDefinition | undefined {
  return MONITORING_CHECK_CATALOG.find((c) => c.id === id);
}
